# Generated by Django 5.1.4 on 2025-05-15 12:55

import django_resized.forms
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("a_users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="image",
            field=django_resized.forms.ResizedImageField(
                blank=True,
                crop=["middle", "center"],
                default="avatars/default.jpg",
                force_format="JPEG",
                help_text="Profile picture, max 300x300 pixels",
                keep_meta=True,
                null=True,
                quality=75,
                scale=None,
                size=[300, 300],
                upload_to="avatars/",
            ),
        ),
    ]
